"""add_assignee_email_column

Revision ID: d29c406e2eae
Revises: dbe23ff288e5
Create Date: 2026-07-22 07:29:13.747835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd29c406e2eae'
down_revision: Union[str, Sequence[str], None] = 'dbe23ff288e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('assignee_email', sa.String(length=254), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'assignee_email')
    # ### end Alembic commands ###
